image: docker:latest
services:
  - docker:dind

stages:
  - build_latest
  - tag_gitlab

before_script:
  - echo Logging in to $CI_REGISTRY...
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  - docker info | grep Registry

build_latest:
  stage: build_latest
  script:
    - apk add --update curl && apk add --update jq && rm -rf /var/cache/apk/*
    - "sh get_tags.sh"
    - "sh build.sh"
  only:
    - master

tag_gitlab:
  stage: tag_gitlab
  script:
    - "sh get_tags.sh"
    - export TAG=`cat latest` 
    - "git tag -a $TAG -m Automated CLI build $TAG'"
