image: docker:latest
services:
  - docker:dind

stages:
  - build_latest

before_script:
  - echo Logging in to $CI_REGISTRY...
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  - docker info | grep Registry

build_latest:
  stage: build_latest
  script:
    - ls
    - ./get_tags.sh
    - ./build.sh
  only:
    - master
