image: docker:latest
services:
  - docker:dind

stages:
  - build_latest

before_script:
  - echo Logging in to $CI_REGISTRY...
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  - docker info | grep Registry

build_latest:
  stage: build_latest
  script:
    - 'export VERSION=`cat latest`'
    - 'export SHELL_VERSION=`cat shell-latest`'
    - 'export latest=`curl -Is https://hub.docker.com/v2/repositories/richarvey/awscli/tags/$(cat latest)/ | head -n 1|cut -d$' ' -f2`'
    - if [ ${latest} == "200" ]; then echo "Build Exists: Nothing to do!" && exit 0 else echo "Building: awscli" && docker build --build-arg VERSION="${VERSION}" -t "richarvey/awscli:${VERSION}" . && docker push "richarvey/awscli:${VERSION}" && docker tag "richarvey/awscli:${VERSION}" richarvey/awscli:latest && docker push richarvey/awscli:latest fi
  only:
    - master
